### ISSUE TITLE
To add user state, city, and postcode in login API

### ISSUE THREAD

**Issue by payen83** [arifahmunirahzul/MMWeb#13]
After user login, response should include user's detail, including city, state and postcode. Currently only email, address, token and user id is available. this cross reference in issue #9

**Comment by arifahmunirahzul** [comment]
**DONE**

![image](https://user-images.githubusercontent.com/38314829/50430625-fc0e7780-08ff-11e9-91b6-a8cae0667028.png)

**Comment by payen83** [comment]
checked and verified. Closed
