### ISSUE TITLE
Add city & state in update profile API

### ISSUE THREAD

**Issue by arifahmunirahzul** [arifahmunirahzul/MMWeb#9]
User can update city and state in update user api

**Comment by arifahmunirahzul** [comment]
**DONE** 

![image](https://user-images.githubusercontent.com/38314829/50322005-58435700-050e-11e9-9ed2-3b3a2a36f250.png)

![image](https://user-images.githubusercontent.com/38314829/50322021-65604600-050e-11e9-8681-4bec23e4844f.png)

(View User Profile)

![image](https://user-images.githubusercontent.com/38314829/50322248-40b89e00-050f-11e9-8a23-9879f6422e9a.png)

**Comment by payen83** [comment]
Thanks will check soon

**Comment by payen83** [comment]
Test and able to add state, city and postcode in API. Closed
